"""empty message

Revision ID: b5b1093f8579
Revises: 3297ca3da739
Create Date: 2022-06-04 20:46:51.507668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b1093f8579'
down_revision = '3297ca3da739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.alter_column('artists', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('artists', 'website')
    op.add_column('venues', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.alter_column('venues', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('venues', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('website', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.alter_column('venues', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('venues', 'website_link')
    op.add_column('artists', sa.Column('website', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.alter_column('artists', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('artists', 'website_link')
    # ### end Alembic commands ###
